"""add negative_whitelist table

Revision ID: f501b86a7e39
Revises: 0001_initial_baseline
Create Date: 2026-04-12 05:29:02.182306+00:00

NOTE: Auto-generated by alembic, then manually cleaned to remove
SQLite false-positive type diffs (TEXT→String, REAL→Float, etc.).
Only the negative_whitelist CREATE TABLE + index are real changes.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f501b86a7e39"
down_revision: Union[str, None] = "0001_initial_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "negative_whitelist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("search_term", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("search_term"),
    )
    with op.batch_alter_table("negative_whitelist", schema=None) as batch_op:
        batch_op.create_index("ix_neg_wl_term", ["search_term"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("negative_whitelist", schema=None) as batch_op:
        batch_op.drop_index("ix_neg_wl_term")

    op.drop_table("negative_whitelist")
